# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

theme:
  name: material

plugins:
  - search
  - mkdocs-jupyter:  # required to convert Jupyter notebooks
      include_source: true
      execute: false
      ignore_h1_titles: true

markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences: {}
  pymdownx.arithmatex: # required for equation display
    generic: true
  pymdownx.snippets: {}

extra_javascript: [
  # requirements for pymdownx.arithmetex:
  "javascripts/mathjax.js",
  "https://polyfill.io/v3/polyfill.min.js?features=es6",
  "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
]

site_name: Contributor Onboarding
repo_url: 'https://github.com/parthapratimkalita/contributor-onboarding'

nav:
- Home: 'index.md'
- Resources:
      - 'resources/github-basics.md'
